import type { NextPage } from "next";
import Head from "next/head";
import styles from "./Post.module.css";
import * as React from "react";
import { signOut, useSession } from "next-auth/react";
import Link from "next/link";
import "react-activity-feed/dist/index.css";
import { connect } from "getstream";
import { Form, Input, Button, Dialog, Card } from "antd-mobile";
import {
  StreamApp,
  NotificationDropdown,
  FlatFeed,
  LikeButton,
  Activity,
  CommentList,
  CommentField,
  StatusUpdateForm,
  FollowButton,
  NotificationFeed,
} from "react-activity-feed";
import stream from "getstream";
import { useContext, useEffect } from "react";
import { useUserState } from "../../../context/user";

const apiKey = process.env.NEXT_PUBLIC_STREAM_API_KEY as string;
const appId = process.env.NEXT_PUBLIC_STREAM_APP_ID as string;

const MakePost = () => {
  const { user } = useUserState();

  const session = useSession();
  const userToken = session.data?.user?.userToken;
  // const username = session.data?.user?.username;

  // const apiKey = process.env.NEXT_PUBLIC_STREAM_API_KEY as string;
  // const appId = process.env.NEXT_PUBLIC_STREAM_APP_ID as string;

  // let stream = require("getstream");

  // const client = stream.connect(apiKey, userToken, appId);

  // For the feed group 'user' and user id 'eric' get the feed
  // The user token is generated server-side for this user

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Home for</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Make a Post</h1>
          <StreamApp apiKey={apiKey} appId={appId} token={userToken}>
            <StatusUpdateForm />
          </StreamApp>
        </main>
      </div>
    </>
  );
};

export default MakePost;
